{{/*
Copyright 2024 Redpanda Data, Inc.

Use of this software is governed by the Business Source License
included in the file licenses/BSL.md

As of the Change Date specified in that file, in accordance with
the Business Source License, use of this software will be governed
by the Apache License, Version 2.0
*/}}

{{- if and .Values.rbac.create .Values.rbac.createRPKBundleCRs }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "redpanda-operator.fullname" . }}-rpk-bundle
  labels:
{{ include "redpanda-operator.labels" . | indent 4 }}
rules:
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterrolebindings
    - clusterroles
  verbs:
    - create
    - get
    - delete
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - nodes
    - configmaps
    - endpoints
    - events
    - limitranges
    - persistentvolumeclaims
    - pods
    - pods/log
    - replicationcontrollers
    - resourcequotas
    - serviceaccounts
    - services
  verbs:
    - get
    - list
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - get
    - list
{{- end }}
